---

- name: Enable ISE OpenAPIs (ISE 3.1+)
  delegate_to: localhost 
  ansible.builtin.uri:
     url: "https://{{ inventory_hostname }}/admin/API/apiService/update"
     method: POST 
     url_username: "{{ ise_username }}" 
     url_password: "{{ ise_password }}"
     force_basic_auth: yes 
     body: '{ "papIsEnabled":true, "psnsIsEnabled":true }'
     status_code: 200,500
     body_format: json
     validate_certs: "{{ ise_verify }}"
     return_content: true 
  register: response 


- name: ISE OpenAPIs Enabled Status 
  when: 